irrigation_unlimited:
  controllers:
    - name: "Controleur 1"
      all_zones_config:
        show:
          timeline: true
        allow_manual: true
        # duration: "0:10:00"
      zones:
        - name: Café François
          zone_id: "1"
          entity_id: switch.vanne_atelier_gui
          maximum: "00:45:00"
        - name: Serre
          zone_id: "2"
          entity_id: switch.vanne_maison_journalier_gui
          maximum: "00:30:00"
        - name: Pelouse
          zone_id: "3"
          entity_id : switch.vanne_jardin_devant_gui
          maximum: "01:10:00"
        - name: Deux carrés
          zone_id: "4"
          entity_id: switch.vanne_deux_carres_gui
          maximum: "00:45:00"
        - name: Un carré
          zone_id: "5"
          entity_id: switch.vanne_un_carre_gui
          maximum: "00:30:00"
        - name: Petits fruits
          zone_id: "6"
          entity_id: switch.vanne_petits_fruits_gui
          maximum: "00:50:00"
        - name: Haie - Céanothe - Fleurs
          zone_id: "7"
          entity_id: switch.vanne_haie_gui
          maximum: "01:00:00"
        - name: Pommiers
          zone_id: "8"
          entity_id: switch.vanne_pommiers_gui
          maximum: "00:30:00"
        - name: Pare-terre Julie 
          zone_id: "9"
          entity_id: switch.vanne_buanderie_grande_maison_gui
          maximum: "00:45:00"
        - name : Haies pelouses
          zone_id: "10"
          entity_id: switch.718
          maximum: "00:45:00"
        - name: If Cour carrée
          entity_id: switch.vanne_salle_claudine_gui
          zone_id: "11"
          maximum: "00:20:00"
        - name: Haie du fond
          zone_id: "12"
          entity_id: switch.vanne_haie_fond_gui
          maximum: "01:40:00"
        - name: Tilleul
          zone_id: "13"
          entity_id: switch.vanne_tilleul_gui
          maximum: "00:40:00"
      sequences:
      - name: nuit
        schedules:
          - name: 1
            time: "22:00"
            schedule_id: "s1"
        zones:
          - zone_id: 1 # Café François
            duration: "00:30"
          - zone_id: 2 # Serre et autres
            duration: "00:20"
          - zone_id: 9 # Pare-terre Julie
            duration: "00:30"
          - zone_id: 4 # Deux carrés
            duration: "00:30"
          - zone_id: 5 # Un carré
            duration: "00:20"
          - zone_id: 6 # Petits fruits
            duration: "00:30"
          - zone_id: 7 # Haie - Céanothe
            duration: "00:40"
          - zone_id: 8 # Pommiers
            duration: "00:20"
          - zone_id: 10 # Haies pelouse
            duration: "00:25"
          - zone_id: 11 # If cour carrée
            duration: "00:10"
          - zone_id: 12 # Haie du fond
            duration: "00:30"            
          - zone_id: 13 # Tilleul - Cerisier
            duration: "00:30"    
          - zone_id: 3 # Pelouse
            duration: "00:40"        
      - name: jour
        duration: "00:05"
        delay: "02:25"
        repeat: 3
        schedules: 
          - name: 2
            time: "12:00"
            schedule_id: "s2"
        zones:
          - zone_id: 2
    - name: "Controleur 2"
      all_zones_config:
        show:
          timeline: false
        allow_manual: true
      zones:
        - name: Aérateur bac
          zone_id: "1"
          entity_id: switch.aerateur_bac
      sequences:
      - name: Bac
        schedules:
          - name: "bac"
            time: "00:15"
            schedule_id: "bac"
        zones:
          - zone_id: 1 # bac
            duration: "00:50"
            delay: "01:40"
            repeat: 6
            
sensor:
  - platform: average
    name: irrigation_unlimited_rain_0
    entities:
      - sensor.414
    precision: 1
    start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) }}"
    end: "{{ now() }}"
    scan_interval: 600

  - platform: average
    name: irrigation_unlimited_rain_1
    entities:
      - sensor.414
    precision: 1
    start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) - timedelta(days=1) }}"
    end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=1) }}"
    scan_interval: 600

  - platform: average
    name: irrigation_unlimited_rain_2
    entities:
      - sensor.414
    precision: 1
    start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) - timedelta(days=2) }}"
    end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=2) }}"
    scan_interval: 600

  - platform: average
    name: irrigation_unlimited_rain_3
    entities:
      - sensor.414
    precision: 1
    start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) - timedelta(days=3) }}"
    end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=3) }}"
    scan_interval: 600

  - platform: average
    name: irrigation_unlimited_rain_4
    entities:
      - sensor.414
    precision: 1
    start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) - timedelta(days=4) }}"
    end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=4) }}"
    scan_interval: 600

  - platform: average
    name: irrigation_unlimited_temperature_0
    entities:
      - sensor.415_1
    precision: 1
    start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) }}"
    end: "{{ now() }}"
    scan_interval: 600

  - platform: average
    name: irrigation_unlimited_temperature_1
    entities:
      - sensor.415_1
    precision: 1
    start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) - timedelta(days=1) }}"
    end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=1) }}"
    scan_interval: 600

  - platform: average
    name: irrigation_unlimited_temperature_2
    entities:
      - sensor.415_1
    precision: 1
    start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) - timedelta(days=2) }}"
    end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=2) }}"
    scan_interval: 600

  - platform: average
    name: irrigation_unlimited_temperature_3
    entities:
      - sensor.415_1
    precision: 1
    start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) - timedelta(days=3) }}"
    end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=3) }}"
    scan_interval: 600

  - platform: average
    name: irrigation_unlimited_temperature_4
    entities:
      - sensor.415_1
    precision: 1
    start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) - timedelta(days=4) }}"
    end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=4) }}"
    scan_interval: 600

  - platform: average
    name: irrigation_unlimited_temperature_5_day_moving_average
    entities:
      - sensor.415_1
    precision: 1
    start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) - timedelta(days=4) }}"
    end: "{{ now() }}"
    scan_interval: 600

  - platform: filter
    name : Consommation pressostat low pass
    entity_id: sensor.pressostat_power
    unique_id: pressostat_power_lowpass
    filters:
      - filter: lowpass
        time_constant: 1
# numéro des electrovannes
# 1 (Input 1): non raccordée
# 2 (Input 2) : Kfé François - idx = 562
# 3 (Input 3): Serre - idx = 564
# 4 (Input 4) : Haie rue - idx = 565
# 5 (Input 5): Cuisine grande maison (raccordé non installée) - idx = 568
# 6 (Input 6) : Pare terre Julie - idx = 569
# 7 (Input 7) : Pelouse - idx = 566
# 8 (Input 9) : Vanne deux carrés  - idx = 713
# 9 (Input 10) : Vanne un carré - idx = 714
# 10 (Input 11) : Vanne petits fruits - idx = 715
# 11 (Input 12) : Vanne Haie - Céanothe et fleurs - idx = 716
# 12 (Input 13) : Vanne Pommiers - idx = 717
# 13 (Input 14) : Non raccordé - idx = 
# 14 (Input 15) : Haie du fond - idx = 719 
# 15 (Input 16) : Tilleul - idx = 720

# Bug si on définit le name en même temps, entity_id prend pour valeur le name au lieu de la référence
# Some kind of tariff must be defined in order to be able to reset counters
utility_meter:
  water_meter_arrosage:
    name: Consommation eau arrosage
    source: sensor.556
    unique_id: "water_meter_arrosage"
    tariffs: 
      - "std"
  water_meter_id2:
    name: Consommation eau kfé francois
    source: sensor.556
    unique_id: "water_meter_id2"
    tariffs: 
      - "std"
  water_meter_id3:
    source: sensor.556
    name: Consommation eau Serre
    unique_id: "water_meter_id3"
    tariffs: 
      - "std"
  water_meter_id4:
    source: sensor.556
    name: Consommation eau Haie rue
    unique_id: "water_meter_id4"
    tariffs: 
      - "std"
  water_meter_id5:
    source: sensor.556
    name: Consommation cuisine grande maison
    unique_id: "water_meter_id5"
    tariffs: 
      - "std"
  water_meter_id6:
    source: sensor.556
    name: Consommation eau pare terre Julie
    unique_id: "water_meter_id6"
    tariffs: 
      - "std"
  water_meter_id7:
    source: sensor.556
    name: Consommation eau Pelouse
    unique_id: "water_meter_id7"
    tariffs: 
      - "std"
  water_meter_id8:
    source: sensor.556
    name: Consommation eau deux carrés
    unique_id: "water_meter_id8"
    tariffs: 
      - "std"
  water_meter_id9:
    source: sensor.556
    name: Consommation eau un carré
    unique_id: "water_meter_id9"
    tariffs: 
      - "std"
  water_meter_id10:
    source: sensor.556
    name: Consommation eau petits fruits
    unique_id: "water_meter_id10"
    tariffs: 
      - "std"
  water_meter_id11:
    source: sensor.556
    name: Consommation eau Haie - Céanothe et fleurs
    unique_id: "water_meter_id11"
    tariffs: 
      - "std"
  water_meter_id12:
    source: sensor.556
    name: Consommation eau Pommiers
    unique_id: "water_meter_id12"
    tariffs: 
      - "std"
  water_meter_id13:
    source: sensor.556
    name: Haie Charme Hêtre pourpre
    unique_id: "water_meter_id13"
    tariffs: 
      - "std"
  water_meter_id14:
    source: sensor.556
    name: Consommation non utilisé
    unique_id: "water_meter_id14"
    tariffs: 
      - "std"
  water_meter_id15:
    source: sensor.556
    name: Consommation eau haie du fond
    unique_id: "water_meter_id15"
    tariffs: 
      - "std"
  water_meter_id16:
    source: sensor.556
    name: Consommation eau Tilleul
    unique_id: "water_meter_id16"
    tariffs: 
      - "std"


input_number:
  water_id2:
    name: Consommation eau Kfé François
    min: 0
    max: 10000
    step: 1
    mode: box
  water_consumption_perhour_id2:
    name: Consommation eau Kfé François par heure
    initial: 0.2
    min: 0.05
    max: 1
    step: 0.05
    mode: box
  water_id3:
    name: Consommation eau Serre
    min: 0
    max: 10000
    step: 1
    mode: box
  water_consumption_perhour_id3:
    name: Consommation eau serre par heure
    initial: 0.4
    min: 0.05
    max: 1
    step: 0.05
    mode: box
  water_id4:
    name: Consommation eau Haie rue
    min: 0
    max: 10000
    step: 1
    mode: box
  water_consumption_perhour_id4:
    name: Consommation eau Haie rue
    initial: 0.3
    min: 0.05
    max: 1
    step: 0.05
    mode: box
  water_id5:
    name: Consommation cuisine grande maison
    min: 0
    max: 10000
    step: 1
    mode: box
  water_consumption_perhour_id5:
    name: Consommation eau cuisine grande maison
    initial: 0.1
    min: 0.05
    max: 1
    step: 0.05
    mode: box
  water_id6:
    name: Consommation pare-terre Julie
    min: 0
    max: 10000
    step: 1
    mode: box
  water_consumption_perhour_id6:
    name: Consommation eau pare-terre Julie
    initial: 0.1
    min: 0.05
    max: 1
    step: 0.05
    mode: box
  water_id7:
    name: Consommation eau Pelouse
    min: 0
    max: 10000
    step: 1
    mode: box
  water_consumption_perhour_id7:
    name: Consommation eau Pelouse
    initial: 0.75
    min: 0.05
    max: 1
    step: 0.05
    mode: box
  water_id8:
    name: Consommation eaux deux carrés
    min: 0
    max: 10000
    step: 1
    mode: box
  water_consumption_perhour_id8:
    name: Consommation eau deux carrés par heure
    initial: 0.1
    min: 0.05
    max: 1
    step: 0.05
    mode: box
  water_id9:
    name: Consommation eau un carré
    min: 0
    max: 10000
    step: 1
    mode: box
  water_consumption_perhour_id9:
    name: Consommation eau un carré par heure
    initial: 0.15
    min: 0.05
    max: 1
    step: 0.05
    mode: box
  water_id10:
    name: Consommation eau petits fruits
    min: 0
    max: 10000
    step: 1
    mode: box
  water_consumption_perhour_id10:
    name: Consommation eau petits fruits par heure
    initial: 0.1
    min: 0.05
    max: 1
    step: 0.05
    mode: box
  water_id11:
    name: Consommation Haie Céanothe et fleurs
    min: 0
    max: 10000
    step: 1
    mode: box
  water_consumption_perhour_id11:
    name: Consommation eau Haie Céanothe et fleurs par heure
    initial: 0.15
    min: 0.05
    max: 1
    step: 0.05
    mode: box
  water_id12:
    name: Consommation eau Pommiers
    min: 0
    max: 10000
    step: 1
    mode: box
  water_consumption_perhour_id12:
    name: Consommation eau Pommiers par heure
    initial: 0.075
    min: 0.05
    max: 1
    step: 0.05
    mode: box
  water_id13:
    name: Consommation Haie Charme Hêtre pourpre
    min: 0
    max: 10000
    step: 1
    mode: box
  water_consumption_perhour_id13:
    name: Consommation eau Haies Charme et Hêtre pourpre par heure
    initial: 0.23
    min: 0.05
    max: 1
    step: 0.05
    mode: box
  water_id14:
    name: Consommation eau TBD
    min: 0
    max: 10000
    step: 1
    mode: box
  water_consumption_perhour_id14:
    name: Consommation eau TDB par heure
    initial: 0.1
    min: 0.05
    max: 1
    step: 0.05
    mode: box
  water_id15:
    name: Consommation eau haie du fond
    min: 0
    max: 10000
    step: 1
    mode: box
  water_consumption_perhour_id15:
    name: Consommation eau Haie du fond par heure
    initial: 0.1
    min: 0.05
    max: 1
    step: 0.05
    mode: box
  water_id16:
    name: Consommation eau Tilleul
    min: 0
    max: 10000
    step: 1
    mode: box
  water_consumption_perhour_id16:
    name: Consommation eau Tilleul par heure
    initial: 0.1
    min: 0.05
    max: 1
    step: 0.05
    mode: box

template: 
  - sensor:
    # Five day weighted rain total sensor.
    # Adjust the weight values (0.7, 0.3, 0.15, 0.05) to suit your needs (0.0 = ignore that day).
    - name: "irrigation_unlimited_rain_weighted_total"
      unit_of_measurement: "mm"
      unique_id: "irrigation_unlimited_0"
      icon: "mdi:umbrella"
      state: >
        {% set r0 = state_attr('sensor.irrigation_unlimited_rain_0','max_value') | float(-1) %}
        {% set r1 = state_attr('sensor.irrigation_unlimited_rain_1','max_value') | float(-1) %}
        {% set r2 = state_attr('sensor.irrigation_unlimited_rain_2','max_value') | float(-1) %}
        {% set r3 = state_attr('sensor.irrigation_unlimited_rain_3','max_value') | float(-1) %}
        {% set r4 = state_attr('sensor.irrigation_unlimited_rain_4','max_value') | float(-1) %}
        {% if r0 != -1 and r1 != -1 and r2 != -1 and r3 != - 1 and r4 != -1 %}
          {% set rain_total = r0 %}
          {% set rain_total = rain_total + r1 * 0.7 %}
          {% set rain_total = rain_total + r2 * 0.3 %}
          {% set rain_total = rain_total + r3 * 0.15 %}
          {% set rain_total = rain_total + r4 * 0.05 %}
          {{ rain_total | round(1) }}
        {% else %}
          {{ -1 }}
        {% endif %}

    - name: "Irrigation Temperature min today"
      unique_id: "Temperature min today"
      state: >
        {{state_attr("sensor.irrigation_unlimited_temperature_0","min_value")}}

    - name: "Irrigation Temperature max today"
      unique_id: "Temperature max today"
      state: >
        {{state_attr("sensor.irrigation_unlimited_temperature_0","max_value")}}

    - name: "Irrigation Smart Evapotranspiration"
      state: >
        {{state_attr("sensor.smart_irrigation_test_hourly_adjusted_run_time_2","evapotranspiration")}}

  # card-templater card_templater
    - unique_id: 722_t
      name: '{{state_attr("sensor.722","description")}}'
      state: '{{states("sensor.722")}}'

    - unique_id: 723_t
      name: '{{state_attr("sensor.723","description")}}'
      state: '{{states("sensor.723")}}'

    - unique_id: 725_t
      name: '{{state_attr("sensor.725","description")}}'
      state: '{{states("sensor.725")}}'

    - unique_id: 726_t
      name: '{{state_attr("sensor.726","description")}}'
      state: '{{states("sensor.726")}}'

input_text:
  smart_irrigation_id7_adjust_time:
    # Lawn
    name: id7 temps arrosage
    initial: ""

input_boolean:
  irrigation_duration_smart:
    # Condition to allow automatic watering upfate
    name: Mise à jour automatique du temps d'arrosage

input_datetime:
  watering_s1_start:
    # Sequence 1 start time
    name: Début arrosage de nuit
    has_date: false
    has_time: true
